### Movies index
GET http://localhost:3000/movies.json

### Movies create
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Test title",
  "year": "Test year",
  "rated": "Test rated",
  "released": "Test released",
  "runtime": "Test runtime",
  "formatted_runtime": "Test formatted runtime",
  "actors": "Test actors",
  "awards": "Test awards",
  "box_office": "Test box office",
  "director": "Test director",
  "genre": "Test genre",
  "language": "Test language",
  "plot": "Test plot",
  "poster": "Test poster",
  "entertainment_type": "Test entertainment type",
  "writer": "Test writer",
  "imdb_id": "Test imdb id",
  "imdb_rating": "Test imdb rating",
  "imdb_votes": "Test imdb voters"
}

### Movies show
GET http://localhost:3000/movies/Deliverance

### ACTION MOVIE REQUESTS

### Action Comedies index
GET http://localhost:3000/action_comedies.json

### Action Dramas index
GET http://localhost:3000/action_dramas.json

### Action Families index
GET http://localhost:3000/action_families.json

### Action Horrors index
GET http://localhost:3000/action_horrors.json

### Action Romances index
GET http://localhost:3000/action_romances.json

### Action Sci-Fis index
GET http://localhost:3000/action_scifis.json

### Action Sports index
GET http://localhost:3000/action_sports.json

### Actions index
GET http://localhost:3000/actions.json

###

### Biographies index
GET http://localhost:3000/biographies.json

### Comedies index
GET http://localhost:3000/comedies.json

### Crimes index
GET http://localhost:3000/crimes.json

### Documentaries index
GET http://localhost:3000/documentaries.json

### Dramas index
GET http://localhost:3000/dramas.json

### Families index
GET http://localhost:3000/families.json

### Horrors index
GET http://localhost:3000/horrors.json

### Romances index
GET http://localhost:3000/romances.json

### Sci-Fis index
GET http://localhost:3000/scifis.json

### Sports index
GET http://localhost:3000/sports.json

### Thrillers index
GET http://localhost:3000/thrillers.json



